# This is the "Build Context" for your site.
[build]
  # Command to run: This tells Netlify to run our new build script.
  command = "npm run build"
  
  # Publish directory: This tells Netlify to deploy the final "dist" folder.
  publish = "dist/"
  
  # Functions directory: This remains the same.
  functions = "netlify/functions"